version: '3'

services:
  epoch-gateway:
    image: epoch-gateway:latest
    container_name: epoch-gateway
    command:
      - "--admin.url=114.67.107.190"
      - "--nacos.url=47.102.158.43"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8888:8888
    restart: on-failure

  epoch-monitor-admin:
    image: epoch-monitor-admin:latest
    container_name: epoch-monitor-admin
    command:
      - "--nacos.url=47.102.158.43"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8090:8090
    restart: on-failure

  epoch-auth-server:
    image: epoch-auth-server:latest
    container_name: epoch-auth-server
    command:
      - "--nacos.url=47.102.158.43"
      - "--admin.url=114.67.107.190"
      - "--mysql.url=114.67.107.190:3306"
      - "--redis.url=47.102.158.43"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8020:8020
    restart: on-failure

  epoch-system:
    image: epoch-system:latest
    container_name: epoch-system
    command:
      - "--nacos.url=47.102.158.43"
      - "--admin.url=114.67.107.190"
      - "--mysql.url=114.67.107.190:3306"
      - "--auth.url=http://114.67.107.190:8020"
      - "--redis.url=47.102.158.43"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 9010:9010
    restart: on-failure

  epoch-generator:
    image: epoch-generator:latest
    container_name: epoch-generator
    command:
      - "--nacos.url=47.102.158.43"
      - "--admin.url=114.67.107.190"
      - "--mysql.url=114.67.107.190:3306"
      - "--auth.url=http://114.67.107.190:8020"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 9030:9030
    restart: on-failure

  epoch-hr:
    image: epoch-hr:latest
    container_name: epoch-hr
    command:
      - "--nacos.url=47.102.158.43"
      - "--admin.url=114.67.107.190"
      - "--mysql.url=114.67.107.190:3306"
      - "--auth.url=http://114.67.107.190:8020"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 9020:9020
    restart: on-failure

