version: '3'

services:
  epoch-gateway:
    image: epoch-gateway:latest
    container_name: epoch-gateway
    command:
      - "--nacos.url=47.102.158.43"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8888:8888
    restart: on-failure

