# server
server:
  port: 9411

# spring
spring:
  application:
    name: epoch-monitor

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://106.53.38.153:8010/eureka/, http://114.67.107.190:8010/eureka/,http://47.102.158.43:8010/eureka/

# zipkin ui配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false