# server
server:
  port: 8888

# spring
spring:
  application:
    name: epoch-gateway

# actuator端点开放规则
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans

# eureka
eureka:
  instance:
    instance-id: epoch-gateway
  client:
    service-url:
      defaultZone: http://106.53.38.153:8010/eureka/, http://114.67.107.190:8010/eureka/,http://47.102.158.43:8010/eureka/

# zuul
zuul:
  routes:
    epoch-base:
      path: /base/**
      serviceId: epoch-base
    epoch-monitor:
      path: /monitor/**
      serviceId: epoch-monitor
    epoch-auth:
      path: /auth/**
      serviceId: epoch-auth
    epoch-test:
      path: /test/**
      serviceId: epoch-test
