# server配置
server:
  port: 9001

# spring
spring:
  application:
    name: epoch-generator

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/epoch?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: marshal1234!

# eureka
eureka:
  instance:
    instance-id: epoch-generator
  client:
    service-url:
      defaultZone: http://106.53.38.153:8010/eureka/, http://114.67.107.190:8010/eureka/,http://47.102.158.43:8010/eureka/
