#单点eureka配置
spring:
  application:
    name: eureka-server

server:
  port: 8010

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否将自己注册到Eureka Server，默认为true,由于当前这个应用就是Eureka Server，故而设为false
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true
    # 1.单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，设为false
    # 2.注册中心进行多副本发布即集群的时候，则设置为true
    fetch-registry: false
    #其他注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8010/eureka